# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1052f65eaf4d789277b9e3d0adae86098cabf1ca137d2af4984de9c46783cd12bd49a351336ec09a6f5fe56696d34b84672bfc05b2e94a8f9913a0f92573e47a

test:
  secret_key_base: aec5efa546f3fb798f0c3d060cd5f35fb2d772c7a5be2091c89a137eecf71c80ec931813915572f4cf25757d577ffffb1c9c2a247481d7305f4fe4b9568d0403

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
