# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d51849c0380be3097c8afbea8ce2c36aaf545ad258a8620016558d0a2f45d87d8ac29351fcd7d4213d7b117f23b37384089091e65725ae6bd4b74ddbfee9d6b1

test:
  secret_key_base: 0bbfce2234a9b1d9a84b83c4b8cbd972ff753977c302701e9fff32c9671c90c8b53e7edbb1b5588ec77647d8ccd36b5c76a9e2bffbaa8eb0a77902cf1195d3ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
