# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb0dcfc5dd80a980acc747508269b8657f8cd66c6b45672a555ff8406420200d91a5f480951b059227a2cbddff3a0128a16954af05114a1fa121265122a7ecf8

test:
  secret_key_base: 220788da8a99d63e819d7bc023f9b68863fa96173793891482301781661663421d2d016dc691dc5225f57b0cae9779b32f192aaa92e86800a104e5f19056be05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
# The following file is used to specify credentials for the remote tests.
# In the CI environment, the environment are populated with proper values.
# If the values are not set, the remote tests will be skipped.
#
# If you want to run remote tests locally, you can set these environment
# variables, or you can create a file `~/.active_shipping/credentials.yml`,
# and set the values in there. This way you won't accidentially commit them
# to git.

usps:
  login: <%= ENV['ACTIVESHIPPING_USPS_LOGIN'] %>

usps_returns:
  mid: <%= ENV['ACTIVESHIPPING_USPS_RETURNS_MID'] %>
  merchant_account_id: <%= ENV['ACTIVESHIPPING_USPS_RETURNS_MERCHANT_ACCOUNT_ID'] %>

ups:
  login: <%= ENV['ACTIVESHIPPING_UPS_LOGIN'] %>
  key: <%= ENV['ACTIVESHIPPING_UPS_KEY'] %>
  password: <%= ENV['ACTIVESHIPPING_UPS_PASSWORD'] %>
  origin_account: <%= ENV['ACTIVESHIPPING_UPS_ORIGIN_ACCOUNT'] %>
  origin_name: <%= ENV['ACTIVESHIPPING_UPS_ORIGIN_NAME'] %>

ups_surepost:
  login: <%= ENV['ACTIVESHIPPING_UPS_SUREPOST_LOGIN'] %>
  key: <%= ENV['ACTIVESHIPPING_UPS_SUREPOST_KEY'] %>
  password: <%= ENV['ACTIVESHIPPING_UPS_SUREPOST_PASSWORD'] %>
  origin_account: <%= ENV['ACTIVESHIPPING_UPS_SUREPOST_ORIGIN_ACCOUNT'] %>
  origin_name: <%= ENV['ACTIVESHIPPING_UPS_SUREPOST_ORIGIN_NAME'] %>

ups_third_party_billing:
  account: <%= ENV['ACTIVESHIPPING_UPS_THIRD_PARTY_BILLING_ACCOUNT'] %>
  zip: <%= ENV['ACTIVESHIPPING_UPS_THIRD_PARTY_BILLING_POSTAL_CODE'] %>
  country_code: <%= ENV['ACTIVESHIPPING_UPS_THIRD_PARTY_BILLING_COUNTRY_CODE'] %>

fedex:
  account: <%= ENV['ACTIVESHIPPING_FEDEX_ACCOUNT'] %>
  login: <%= ENV['ACTIVESHIPPING_FEDEX_LOGIN'] %>
  password: <%= ENV['ACTIVESHIPPING_FEDEX_PASSWORD'] %>
  key: <%= ENV['ACTIVESHIPPING_FEDEX_KEY'] %>

shipwire:
  login: <%= ENV['ACTIVESHIPPING_SHIPWIRE_LOGIN'] %>
  password: <%= ENV['ACTIVESHIPPING_SHIPWITE_PASSWORD'] %>

canada_post:
  login: <%= ENV['ACTIVESHIPPING_CANADA_POST_LOGIN'] %>

new_zealand_post:
  key: <%= ENV['ACTIVESHIPPING_NEW_ZEALAND_POST_KEY'] %>

canada_post_pws:
  customer_number: <%= ENV['ACTIVESHIPPING_CANADA_POST_PWS_CUSTOMER_NUMBER'] %>
  api_key: <%= ENV['ACTIVESHIPPING_CANADA_POST_PWS_API_KEY'] %>
  secret: <%= ENV['ACTIVESHIPPING_CANADA_POST_PWS_SECRET'] %>

canada_post_pws_platform:
  platform_id: <%= ENV['ACTIVESHIPPING_CANADA_POST_PWS_PLATFORM_PLATFORM_ID'] %>
  customer_number: <%= ENV['ACTIVESHIPPING_CANADA_POST_PWS_PLATFORM_CUSTOMER_NUMBER'] %>
  api_key: <%= ENV['ACTIVESHIPPING_CANADA_POST_PWS_PLATFORM_API_KEY'] %>
  secret: <%= ENV['ACTIVESHIPPING_CANADA_POST_PWS_PLATFORM_SECRET'] %>

stamps:
  integration_id: <%= ENV['ACTIVESHIPPING_STAMPS_INTEGRATION_ID'] %>
  username: <%= ENV['ACTIVESHIPPING_STAMPS_USERNAME'] %>
  password: <%= ENV['ACTIVESHIPPING_STAMPS_PASSWORD'] %>

australia_post:
  api_key: <%= ENV['ACTIVESHIPPING_AUSTRALIA_POST_API_KEY'] %>

# fedex_freight:
#   account: FedExFreightAccountNumber
#   shipping_address1: FedExShippingAddress1
#   shipping_address2: FedExShippingAddress2
#   shipping_city: FedExShippingCity
#   shipping_postal_code: FedExShippingPostalCode
#   shipping_state: FedExShippingState
#   shipping_country: FedExShippingCountry
#   billing_address1: FedExBillingAddress1
#   billing_address2: FedExBillingAddress2
#   billing_city: FedExBillingCity
#   billing_postal_code: FedExBillingPostalCode
#   billing_state: FedExBillingState
#   billing_country: FedExBillingCountry
#   payment_type: SENDER
#   freight_class: CLASS_050
#   packaging: PALLET
#   role: SHIPPER
